### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by skosgi242** [lwang114/UnsupTTS#2]
Hi, How do I run inference for some text samples on pre-trained models.

**Comment by lwang114** [comment]
The inference for the TTS model should follow the standard ESPNet pipeline as described in this colab notebook: https://colab.research.google.com/github/espnet/notebook/blob/master/tts_realtime_demo.ipynb#scrollTo=3lMJyJcLCsd4. Our API may be slightly outdated though, so we will consider providing some example code for off-the-shell inference in the future.

**Comment by skosgi242** [comment]
Thanks for the info.
